export const GET_PROJECT_LIST = "GET_PROJECT_LIST"
export const ADD_PROJECT = "ADD_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const UPDATE_TASK_LIST = "GET_TASK_LIST"
export const ADD_TASK = "ADD_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";

export const UPDATE_CURRENT_PROJECT_ID = "UPDATE_CURRENT_PROJECT_ID";
export const UPDATE_CURRENT_TASK_ID = "UPDATE_CURRENT_TASK_ID";